from __future__ import annotations

import json
import os
import shutil
import subprocess
import re
from pathlib import Path

from .geometry import camera_center_to_tvec, opk_to_world_to_camera, rotation_to_quaternion_wxyz
from .parsers.campos import parse_campos
from .parsers.metashape_xml import extract_intrinsics

IMAGE_NUMBER_RE = re.compile(r"image[_-]?0*(\d+)", re.IGNORECASE)


def natural_image_key(path_or_name: str) -> tuple[int, str]:
    name = Path(path_or_name).name
    match = IMAGE_NUMBER_RE.search(name)

    if match:
        return int(match.group(1)), name

    numbers = re.findall(r"\d+", name)
    if numbers:
        return int(numbers[0]), name

    return 10**12, name


def _materialize_file(src: Path, dst: Path, mode: str = "copy") -> None:
    """Place one image in the export dataset.

    Modes:
      copy     : byte-for-byte copy. Slowest, but fully portable.
      hardlink : no data copy when source and destination are on the same filesystem.
      symlink  : relative symbolic link. Fastest, but depends on source path remaining valid.
      reflink  : copy-on-write clone via `cp --reflink=auto`; falls back to copy on unsupported filesystems.
      auto     : hardlink first, then reflink, then copy.

    The function never overwrites an existing destination.
    """
    if dst.exists() or dst.is_symlink():
        return

    dst.parent.mkdir(parents=True, exist_ok=True)
    mode = mode.lower()

    if mode not in {"copy", "hardlink", "symlink", "reflink", "auto"}:
        raise ValueError(f"Unknown image materialization mode: {mode}")

    if mode == "copy":
        shutil.copy2(src, dst)
        return

    if mode == "symlink":
        rel = os.path.relpath(src, start=dst.parent)
        dst.symlink_to(rel)
        return

    if mode in {"hardlink", "auto"}:
        try:
            os.link(src, dst)
            return
        except OSError:
            if mode == "hardlink":
                raise

    if mode in {"reflink", "auto"}:
        try:
            subprocess.run(
                ["cp", "--reflink=auto", "--preserve=timestamps", str(src), str(dst)],
                check=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            return
        except Exception:
            if mode == "reflink":
                raise

    shutil.copy2(src, dst)


def build_ucds(
    images: str | Path,
    campos: str | Path,
    xml: str | Path,
    out: str | Path,
    dataset_id: str | None = None,
    image_mode: str = "copy",
) -> Path:
    images = Path(images)
    campos = Path(campos)
    xml = Path(xml)
    out = Path(out)
    dataset_id = dataset_id or out.name
    out.mkdir(parents=True, exist_ok=True)
    (out / "images").mkdir(exist_ok=True)

    calibration = extract_intrinsics(xml)
    records = sorted(parse_campos(campos), key=lambda rec: natural_image_key(rec.image_name))

    poses = []
    missing = []
    for idx, rec in enumerate(records, start=1):
        img_src = images / rec.image_name
        if not img_src.exists():
            missing.append(rec.image_name)
            continue

        img_dst = out / "images" / rec.image_name
        _materialize_file(img_src, img_dst, mode=image_mode)

        r = opk_to_world_to_camera(rec.omega, rec.phi, rec.kappa)
        q = rotation_to_quaternion_wxyz(r)
        t = camera_center_to_tvec(r, [rec.x, rec.y, rec.z])

        poses.append(
            {
                "image_id": idx,
                "image_name": rec.image_name,
                "camera_center": [rec.x, rec.y, rec.z],
                "opk_degrees": [rec.omega, rec.phi, rec.kappa],
                "accuracy": rec.accuracy,
                "qvec_wxyz": list(q),
                "tvec": list(t),
            }
        )

    if missing:
        raise FileNotFoundError(f"{len(missing)} image(s) listed in CamPos were not found, first missing: {missing[:5]}")

    (out / "calibration.json").write_text(json.dumps(calibration, indent=2), encoding="utf-8")
    (out / "poses.json").write_text(
        json.dumps(
            {
                "coordinate_system": "disc3d_world_mm",
                "rotation_convention": "world_to_camera",
                "poses": poses,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    (out / "metadata.json").write_text(
        json.dumps(
            {
                "dataset_id": dataset_id,
                "n_images": len(poses),
                "source_images": str(images),
                "source_campos": str(campos),
                "source_xml": str(xml),
                "image_materialization": image_mode,
                "notes": "Generated by disc3d-ucds-etl.",
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    (out / "dataset.json").write_text(
        json.dumps(
            {
                "ucds_version": "0.2",
                "dataset_id": dataset_id,
                "image_dir": "images",
                "calibration_file": "calibration.json",
                "poses_file": "poses.json",
                "metadata_file": "metadata.json",
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    return out / "dataset.json"
