from __future__ import annotations

import json
import shutil
from pathlib import Path

from .geometry import camera_center_to_tvec, opk_to_world_to_camera, rotation_to_quaternion_wxyz
from .parsers.campos import parse_campos
from .parsers.metashape_xml import extract_intrinsics


def build_ucds(images: str | Path, campos: str | Path, xml: str | Path, out: str | Path, dataset_id: str | None = None) -> Path:
    images = Path(images)
    out = Path(out)
    dataset_id = dataset_id or out.name
    out.mkdir(parents=True, exist_ok=True)
    (out / "images").mkdir(exist_ok=True)

    calibration = extract_intrinsics(xml)
    records = parse_campos(campos)

    poses = []
    missing = []
    for idx, rec in enumerate(records, start=1):
        img_src = images / rec.image_name
        if not img_src.exists():
            missing.append(rec.image_name)
            continue

        img_dst = out / "images" / rec.image_name
        if not img_dst.exists():
            shutil.copy2(img_src, img_dst)

        r = opk_to_world_to_camera(rec.omega, rec.phi, rec.kappa)
        q = rotation_to_quaternion_wxyz(r)
        t = camera_center_to_tvec(r, [rec.x, rec.y, rec.z])

        poses.append(
            {
                "image_id": idx,
                "image_name": rec.image_name,
                "camera_center": [rec.x, rec.y, rec.z],
                "opk_degrees": [rec.omega, rec.phi, rec.kappa],
                "accuracy": rec.accuracy,
                "qvec_wxyz": list(q),
                "tvec": list(t),
            }
        )

    if missing:
        raise FileNotFoundError(f"{len(missing)} image(s) listed in CamPos were not found, first missing: {missing[:5]}")

    (out / "calibration.json").write_text(json.dumps(calibration, indent=2), encoding="utf-8")
    (out / "poses.json").write_text(
        json.dumps(
            {
                "coordinate_system": "disc3d_world_mm",
                "rotation_convention": "world_to_camera",
                "poses": poses,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    (out / "metadata.json").write_text(
        json.dumps(
            {
                "dataset_id": dataset_id,
                "n_images": len(poses),
                "source_campos": str(campos),
                "source_xml": str(xml),
                "notes": "Generated by disc3d-ucds-etl.",
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    (out / "dataset.json").write_text(
        json.dumps(
            {
                "ucds_version": "0.1",
                "dataset_id": dataset_id,
                "image_dir": "images",
                "calibration_file": "calibration.json",
                "poses_file": "poses.json",
                "metadata_file": "metadata.json",
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    return out / "dataset.json"
